[aliases]
    cat = "pygmentize -g"
    ls = "eza"
    lg = "lazygit"
    dig = "doggo"
    j = "just"
    jg = "just -g"
    gpc = "gh pr create"
    gpv = "gh pr view"
    gpm = "gh pr merge && git pull --ff-only"

[paths]
    bun_home = "$HOME/.bun"
    pnpm_home = "$HOME/Library/pnpm"
    android_home = "$HOME/Library/Android/sdk"
