[settings]
experimental = true
auto_install = true

[tools]
# language
java = "21.0.2"
node = "22.21.1"
python = "3.14.2"

# package manager
gradle = "9.2.1"
pnpm = "10.22.0"
yarn = "4.12.0"
bun = "1.3.2"

# cli
pulumi = "3.219.0"
wrangler = "4.63.0"
1password = "2.32.1"
awscli = { version = "2.33.16", symlink_bins = "true" }

# utilities
flyway = "11.20.3"
"aqua:tailscale/tailscale" = "1.94.1"
